channels:
  - defaults
  - pytorch
  - nvidia
  - pyg
dependencies:
  - cudatoolkit
  - numpy=1.26.2
  - pytorch=2.1.1
  - scikit-learn=1.3.0
  - loguru=0.5.3
  - botorch=0.9.5
  - gpytorch=1.11
  - pandas=2.1.4
  - scipy=1.11.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - ipython=8.19.0
  - dscribe=2.1.0
  - rdkit
